import "./globals.css";
import Header from "@/components/header";
export const metadata = {
  title: "Movier",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div />
      <body>
        <Header />
        {children}
      </body>
      <div />
    </html>
  );
}
