import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Providers } from "./providers";
export const metadata = {
  title: "Movier",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <div className="px-10">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
