import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
export const metadata = {
  title: "Movier",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="px-10">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
